# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='ЧПУ категории')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, verbose_name='ЧПУ товара')),
                ('image', models.ImageField(blank=True, upload_to='products/%m.%Y/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('in_stock', models.IntegerField(db_index=True, default=0, verbose_name='Кол-во в наличии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Товар добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Товар обновлен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
                'verbose_name': 'Товар',
            },
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
